CREATE SCHEMA IF NOT EXISTS user_data;

DROP TABLE IF EXISTS user_data.users;

CREATE TABLE user_data.users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    age INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_data TO dev;
GRANT USAGE ON SCHEMA user_data TO dev;
